export const paymentModeOptions = [
  { label: 'G PAY', value: 'G PAY' },
  { label: 'A/C', value: 'A/C' },
  { label: 'BANK DEPOSIT', value: 'BANK DEPOSIT' },
  { label: 'BY CASH', value: 'BY CASH' },
  { label: 'A/C SAUDI', value: 'A/C SAUDI' },
  { label: 'SHAHUL GPAY', value: 'SHAHUL GPAY' },
  { label: 'SH FDRL', value: 'SH FDRL' },
  { label: 'ANJUB A/C', value: 'ANJUB A/C' },
  { label: 'S AMEER A/C', value: 'S AMEER A/C' },
  { label: 'SH ICICI', value: 'SH ICICI' },
  { label: 'NAJMU A/C', value: 'NAJMU A/C' },
  { label: 'AGENCY', value: 'AGENCY' },
  { label: 'HDFC', value: 'HDFC' },
  { label: 'SBI', value: 'SBI' },
  { label: 'Others', value: 'Others' },
];
