export const TRANSACTION_PURPOSES = [
  { value: 'Job Visa', label: 'Job Visa' },
  { value: 'Umra Visa', label: 'Umra Visa' },
  { value: 'Work Visa', label: 'Work Visa' },
  { value: 'Visiting Visa', label: 'Visiting Visa' },
  { value: 'Attestation', label: 'Attestation' },
  { value: 'Ticket', label: 'Ticket' },
  { value: 'Medical', label: 'Medical' },
  { value: 'VFS Approvement', label: 'VFS Approvement' },
  { value: 'Emigration', label: 'Emigration' },
  { value: 'Translation', label: 'Translation' },
  { value: 'Visa Stamping', label: 'Visa Stamping' },
  { value: 'Job Search Visa', label: 'Job Search Visa' },
  { value: 'TC Appointment', label: 'TC Appointment' },
  { value: 'Gamca Appointment', label: 'Gamca Appointment' },
  { value: 'Others', label: 'Others' },
];
